### ISSUE TITLE
Not possible to change exchange type

### ISSUE THREAD

**Issue by jaumeavila** [mookofe/tail#11]
Hi, 
According to the documentation, the exchange type should be possible to change, but when added in the array of configuration ('exchange_type' => 'topic'), I get this error:
[Mookofe\Tail\Exceptions\InvalidOptionException]
  Option [exchange_type] is not valid

Also, according to the code in Connection.php , which is:
$this->AMQPConnection = new AMQPConnection($this->host, $this->port, $this->username, $this->password, $this->vhost);
            $this->channel = $this->AMQPConnection->channel();
            $this->channel->queue_declare($this->queue_name, false, true, false, false);
            $this->channel->exchange_declare($this->exchange, 'direct', false, true, false);
            $this->channel->queue_bind($this->queue_name, $this->exchange);

The exchange type is hardcoded always in 'direct' and the durable and other parameters are not changeable.

Thanks,
Jaume

**Comment by mookofe** [comment]
Taking a look.

Thanks @jaumeavila

**Comment by jaumeavila** [comment]
And I have seen that this class:
`$this->AMQPConnection = new AMQPConnection($this->host, $this->port, $this->username, $this->password, $this->vhost);`
Is deprecated:

`/**
- Class AMQPConnection
  *
- Kept for BC
  *
- @deprecated
  */
  class AMQPConnection extends AMQPStreamConnection
  {
  }`

Thanks!
Jaume

**Comment by jaumeavila** [comment]
Hi @mookofe ,
Have you been able to make the changes?
Every time I deploy my application my deployment tool overwrites the file and I have to change it manually.

Thanks,
Jaume

**Comment by jaumeavila** [comment]
Hi, 
I have just seen when doing the queue_bind it is always set the routin_key to ''.
Isn't there a way to set a different routing key?

Thanks, 
Jaume

**Comment by mookofe** [comment]
I'll be deploying the fix today @jaumeavila

**Comment by mookofe** [comment]
Issue solved Ref: https://github.com/mookofe/tail/pull/12
