### ISSUE TITLE
Tail class can not be found

### ISSUE THREAD

**Issue by muratak18** [mookofe/tail#17]
Hi,
I'm using Lumen 5.2 and I've already done what you say to integrate it.
In my controller I use it like this : 
Tail::add('test', 'message');

it gives me this error : 
Fatal error: Class 'App\Http\Controllers\Tail' not found

$app->withFacades(); is active in app.php

What should I do?

**Comment by muratak18** [comment]
my mistake, I've should called it \Tail

**Comment by mookofe** [comment]
NP @muratak18!!
