### ISSUE TITLE
Durable

### ISSUE THREAD

**Issue by mage95** [mookofe/tail#18]
Hello how i can overwrite the durability setting? because when i want to consume a message i got this kind of message 

`[Exception]
  PhpAmqpLib\Exception\AMQPProtocolChannelException: PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'exchnge_name' in vhost '/': received 'true' but current is 'false' in \vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\AMQPChannel.php:188`

**Comment by smartyaunt** [comment]
I have same problem,

**Comment by itrack** [comment]
+1

**Comment by M4rcDev** [comment]
+1

**Comment by M4rcDev** [comment]
I fixed it in my fork, lets hope it gets merged.
