### ISSUE TITLE
Question: How do I start the consumers?!??!

### ISSUE THREAD

**Issue by amandiobm** [mookofe/tail#21]
Hello guys, how do I start the consumers!?!?!

Add new message OK, but I can't process that message in queue.

**Comment by mookofe** [comment]
Hello @amandiobm take a look at this example: https://github.com/mookofe/tail#listening-queues

You can wrap the listen block into a infinite while, that way you're always listening.

```
while (true) {
    Tail::listen('queue-name', function ($message) {                
        //Your message logic code
    });
}
```

**Comment by amandiobm** [comment]
@mookofe, but how to run this closure based listener? Using `php artisan queue:listen`? Or I have to create a command e run that command as a queue listener?

**Comment by mookofe** [comment]
Yes @amandiobm, you're going to have to create a command for that. Eventually we might integrate it as a driver for Laravel.
