### ISSUE TITLE
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

### ISSUE THREAD

**Issue by Bebbolus** [mookofe/tail#6]
Loading composer repositories with package information  
Updating dependencies (including require-dev)                                                                
- Installing videlalvaro/php-amqplib (v2.6.2)  
  Downloading: 100%                                                                                        
- Installing mookofe/tail (v1.0.3)  
  Downloading: 100%                                                                                        

videlalvaro/php-amqplib suggests installing ext-sockets (Use AMQPSocketConnection)  
Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

**Comment by mookofe** [comment]
Thanks @Bebbolus, working on it. Will be included in version [v1.0.4](https://github.com/mookofe/tail/milestones/v1.0.4)

**Comment by Bebbolus** [comment]
thak you!
